apiVersion: v1
kind: PersistentVolume
metadata:
  name: openvpn-pv
spec:
  storageClassName: ""
  capacity:
    storage: 1G
  accessModes:
    - ReadWriteOnce
  gcePersistentDisk:
    pdName: gke-zihao-38233c1e-dyn-pvc-8f7c51ba-3309-11e8-a750-42010a8a020f
    fsType: ext4
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openvpn-pvc
spec:
  # It's necessary to specify "" as the storageClassName
  # so that the default storage class won't be used, see
  # https://kubernetes.io/docs/concepts/storage/persistent-volumes/#class-1
  storageClassName: ""
  volumeName: openvpn-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1G
