image:
  repository: zihao/play
  tag: external-dns
  pullPolicy: Always
sources:
  - service
rbac:
  create: true
extraArgs:
  publish-host-ip: ''
logLevel: debug
tolerations:
- key: "node.kubernetes.io/unreachable"
  operator: "Exists"
  effect: "NoExecute"
  tolerationSeconds: 10
