helmDefaults:
  tillerless: true

repositories:
- name: jetstack
  url: https://charts.jetstack.io

releases:
- name: cert-manager
  namespace: cert-manager
  chart: jetstack/cert-manager
  hooks:
  - events: ["presync"]
    showlogs: true
    command: bash
    args:
    - -c
    - |
      kubectl apply -f https://raw.githubusercontent.com/jetstack/cert-manager/release-0.10/deploy/manifests/00-crds.yaml \
        -f ./namespace.yaml
  - events: ["postsync"]
    showlogs: true
    command: bash
    args:
    - -c
    - kubectl apply -f ./letsencrypt-staging.yaml -f ./letsencrypt-prod.yaml
